//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>
#include <vector>
#include <conio.h>
#include <math.h>
using namespace std;

#define MAX_INT 4000000

int fib(const int x) {
	if (x == 0 || x == 1) return 1;
	else return fib (x - 1) + fib (x - 2);
}

int main() {
	int i = 0, term, sum = 0;
	bool less = true;
	while (less) {
		term = fib(i);
		if (term < MAX_INT) {
			if (term % 2 == 0) {
				sum += term;
				cout << "Inserted for fib(" << i << ") : " << term << endl;
				i++;
			}
			else i++;
		}
		else break;
	}
	cout << "The sum of all the even terms below 4,000,000 is: " << sum;
}